site_name: Archimedes

theme:
  name: material

nav:
  - "index.md"
  - Overview: "root_readme.md"

  - "Developer Notes":
    - "developer_notes/doit_vs_own.md"

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
